spring.application.name=ticket-service
spring.datasource.url=jdbc:postgresql://localhost:5433/ticket_db
spring.datasource.username=ticket
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8002

springdoc.swagger-ui.path=/swagger-ui.html

eureka.client.serviceUrl.defaultZone=http://localhost:8003/eureka